//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlusManagementSystem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionProducts
    {
        public int ProductionID { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public int ProductKey { get; set; }
        public decimal Weight { get; set; }
        public int ProductionMaterialKey { get; set; }
    
        public virtual ProductionMaterials ProductionMaterials { get; set; }
        public virtual Products Products { get; set; }
    }
}
