//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BurgerPlusManagementSystem.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSpecifications
    {
        public int ProductSpecificationID { get; set; }
        public int ProductionProductKey { get; set; }
        public int ManufacturerKey { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Products Products { get; set; }
    }
}
